Feature/profile page details
panppp119/touch-in-app pull request #5
Opened 2020-04-27 10:16 UTC by jai-pornpawit

2020-04-27 12:11 UTC, panppp119 commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
font-awesome ให้ add แบบ package ดีกว่า ไม่แนะนำให้ใช้วิธีนี้

2020-04-27 12:46 UTC, panppp119 commented on src/pages/Profile-Overview/Profile-Overview.js
> +import './profile.scss'
ชื่อไฟล์น่าจะผิด

2020-04-27 12:47 UTC, panppp119 commented on src/pages/Profile-Overview/Profile-Overview.js
> +export class Profile extends Component {
พยายามตั้งชื่อตามชื่อไฟล์ แต่ไม่ควรมี -

2020-04-27 12:48 UTC, panppp119 commented on src/pages/Profile-Overview/Profile-Overview.js
> +                    <h3><div className="title-icon"><i class="fa fa-fw fa-briefcase" ></i></div>สถานะการทำงาน</h3>
class ต้องเปลี่ยนเป็น className แต่เพราะมันเป็น fontawesome ลอง yarn add แพคเกจของ fontawesome แล้วใช้ component ของเขาเลยน่าจะดีกว่า แต่ถ้าอยากได้ icon แบบทั้งหมดลง react-icons ตัวนี้ก็ได้

2020-04-27 12:49 UTC, panppp119 commented on src/pages/Profile-Overview/Profile-Overview.js
> +                    <h3><div className="title-icon"><i class="fa fa-fw fa-bed" ></i></div>สิทธิ์การลา</h3>
class => className

2020-04-27 12:50 UTC, panppp119 commented on src/pages/Profile-Overview/Profile-Overview.scss
> +
ด้วยความที่มันเป็น .scss ไม่ใช่ .css มันสามารถซ้อนเข้าไปด้านในได้ ลองดูตัวอย่างใน components/nav/Menu/Menu.scss เป็นตัวอย่างได้ ส่วน @media ไม่มีวิธีที่ตายตัวแล้วแต่จะเลือก แต่ตกลงกับคนที่พัฒนาร่วมกันให้ไปในทิศทางเดียวกัน

2020-04-27 12:51 UTC, panppp119 requested changes
โฟลเดอร์ Profile-Overview ควรอยู่ภายใต้โฟลเดอร์ Profile เพราะเดี๋ยวมันจะมี Profile-History อีก มันควรจะจัดอยู่ในโฟลเดอร์เดียวกัน
src > pages > Profile > Profile-Overview
และเพิ่ม index ใต้ Profile แล้วใส่ route ให้มัน เช่น

`<Switch>
        <Route exact path={`${match.url}`} component={ProfileOverview} />
      </Switch>`

match มาจาก this.props.match ลองดูตัว withRouter ของ react-router-dom

![scrnli_4_27_2020_8-10-37 PM](https://user-images.githubusercontent.com/24587745/80376104-86cfff80-88c3-11ea-9ddd-94005dcd69c1.png)

ปรับก่อนนะ ถึงจะ aprrove ให้ :)

2020-04-27 15:15 UTC, panppp119 commented on src/pages/Profile-Overview/Profile-Overview.scss
> +@media (min-width: 1280px) {
ใช้ @media ครั้งเดียวก็ได้ แล้วใส่พวก .class ด้านใน เช่น
`@medai (min-width: 1280px) { 
.border { ... } 
.title-bar { ... }
}`

2020-04-28 08:40 UTC, jai-pornpawit commented on src/pages/Profile-Overview/Profile-Overview.scss
> +@media (min-width: 1280px) {
แก้ไขแล้วครับ 👨‍💻👨‍💻👨‍💻

2020-04-28 08:42 UTC, jai-pornpawit commented on src/pages/Profile-Overview/Profile-Overview.js
> +import './profile.scss'
แก้ไขแล้วครับ 👨‍💻👨‍💻👨‍💻

2020-04-28 08:42 UTC, jai-pornpawit commented on src/pages/Profile-Overview/Profile-Overview.js
> +export class Profile extends Component {
แก้ไขแล้วครับ 👨‍💻👨‍💻👨‍💻

2020-04-28 09:58 UTC, jai-pornpawit commented on public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
แก้ไขเรียบร้อยแล้วครับ ใช้ react icon แทนครับ

2020-04-28 09:58 UTC, jai-pornpawit commented on src/pages/Profile-Overview/Profile-Overview.js
> +                    <h3><div className="title-icon"><i class="fa fa-fw fa-bed" ></i></div>สิทธิ์การลา</h3>
แก้ไขเรียบร้อยแล้วครับ 👨‍💻👨‍💻👨‍💻

2020-04-29 02:13 UTC, panppp119 commented on src/pages/Profile/Profile-Overview/ProfileOverview.js
> +      <div className='profile-overview'>
เหมือนมันยังแสดงผลบน mobile ยังไม่ค่อยโอเค
![Screen Shot 2563-04-29 at 09 11 19](https://user-images.githubusercontent.com/24587745/80555190-bc770480-89f9-11ea-8422-8da075f2d207.png)

2020-04-29 04:09 UTC, jai-pornpawit commented on src/pages/Profile/Profile-Overview/ProfileOverview.js
> +      <div className='profile-overview'>
แก้ไขแล้วนะครับ 👨‍💻👨‍💻👨‍💻

2020-04-30 04:22 UTC, panppp119 approved these changes

2020-04-30 04:22 UTC, merged